 import React from 'react';

 const machines = [ 
    {id: 1,
     time: '8-9am',
     status: true,
     price: '#1000',
    },
    {id: 2,
        time: '9-10am',
        status: true,
        price: '#1000',
    },
       {id: 3,
        time: '10-11am',
        status: true,
        price: '#1000',
       },
       {id: 4,
        time: '11-12pm',
        status: true,
        price: '#1000',
       },
       {id: 5,
        time: '12-01pm',
        status: true,
        price: '#1000',
       },
       {id: 6,
        time: '1-02pm',
        status: true,
        price: '#1000',
       },
       {id: 7,
        time: '2-03pm',
        status: true,
        price: '#1000',
       },
       {id: 8,
        time: '3-4pm',
        status: true,
        price: '#1000',
       },
]


export default machines;